/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:178f6622-06cd-4722-b5eb-e2a245ae6f93",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ONi9AvTEp",
    "aws_user_pools_web_client_id": "43jjvd5vqcrs2mf4u7ltoo2670",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://stuyybadyffgbjmssdzlr7bdqm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-bc37dx4vjzeyvjpwfn4aoqiwj4",
    "aws_user_files_s3_bucket": "awstutorialdbf1cfb99ac44ee3a77c180430973edd173523-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
